@include('admin.layouts.header')
@include('admin.layouts.sidebar')
@include('admin.layouts.content')
@include('admin.layouts.footer')
@include('admin.layouts.header')
@include('admin.layouts.sidebar')
@include('admin.layouts.content')
@include('admin.layouts.footer')
